[colt]
defeat = 143
victory = 72
draw = 3

[total]
defeat = 10
victory = 4
draw = 0

[rosa]
defeat = 15
victory = 19
draw = 0

[dynamike]
defeat = 165
victory = 131
draw = 2

[brock]
defeat = 161
victory = 122
draw = 2

[shelly]
defeat = 94
victory = 103
draw = 4

[8bit]
defeat = 11
victory = 5
draw = 0

[alli]
defeat = 6
victory = 6
draw = 0

[doug]
defeat = 86
victory = 51
draw = 2

[surge]
defeat = 0
victory = 0
draw = 0

[bo]
defeat = 0
victory = 0
draw = 0

[belle]
defeat = 0
victory = 0
draw = 0

[kit]
defeat = 0
victory = 0
draw = 0
